if: NOT tag IS blank

language: minimal

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
  - os: linux
    dist: trusty

# Super secret password to decrypt the private signing key
env:
  global:
    secure: "t+I0mwf4N8lj+GB9eU1l8paxoD1pzLXBwqYvVQYlF3C/hpLEVWzmzmbtwgVW7+fo2D1TSBibPiz8BDhbRlvqVUVavj4j0T6bBaaZ8fzge/TCyfQfzZePqkS4QsVZpxBFEAF1+eQTSN2i+an028PPkqr9JD9GJvcZt5PLmYy5HwDLSmgNf9Ax4gV5ATUKHZVzbQomqmOU0P0wZriC7KRdIStIoO3DLroLRQv+2z35FPU8Kln6GLTVGklTLZeZ4X1/I0Jw0wMMUKjMouofESjgXUIw+vuOninuyKcxL2Ithm1u2e66z8FVKspJ9fY4oWaC87xAMr3LBn3L1atpfjm99YOuEAKCenjaHDmzDDJOT6sSup9JpUQjooH/wXuIznFXKvLre8+d+chv3gW5oNZtIBktrzEWmze87nbGidArMbGx3S3Ll+4dU3o/0qJbIZRi5li19esYsbY6ojIHjvjZNOghFlJYQ2BgW+xecI6Gp5KUma/HMdT81mcpuNvVH/Oo/sH8aFbJY+rxlH252kQHzeE16LZnrdITx6ECCGI41GH323EWyGLPpEXeeBNtcZXD/8B4om/q7rQxGD6IyWgQ/YRrctJ/Te4uA+ZRPXq1f91wrOtXIf8JwHSQ9lXGFNSVXCBIyDBGC1J02Sgi8QgYVs5qMl39FqcnaWP1kM+flm8="

# Skip installation phase
install: true

before_script:
    - . ./.ci/before_script.sh

script: 
    - . ./.ci/script.sh

# skip-cleanup: true -> Prevent deletion of created artifacts after install and before deployment
deploy:
  - provider: releases
    api_key:
      secure: $GITHUB_API_KEY
    file:
    - $release_zip
    - $release_hash
    - $release_gpg
    skip-cleanup: true
    overwrite: true
    draft: false
    prerelease: true
    on:
     repo: JanMosigItemis/yubiset
     tags: true
